# http://jekyllrb.com/docs/continuous-integration/
language: ruby
rvm:
- 2.3.3

before_install:
 - cp deploy/Gemfile Gemfile
 - cp deploy/Gemfile.lock Gemfile.lock
 - cp deploy/jekyll-serve jekyll-serve
 - cp deploy/versions.json versions.json

before_script:
 - chmod +x ./_scripts/cibuild 

install: 
 - gem install jekyll
 - gem install html-proofer 

script: ./_scripts/cibuild

git:
  submodules: false

branches:
  only:
  - gh-pages     

notifications:
 webhooks:
    urls:
      - https://webhooks.gitter.im/e/b907f0e1ee5f192cba70
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
