# http://jekyllrb.com/docs/continuous-integration/
language: ruby
rvm:
- 2.1

before_script:
 - chmod +x ./_scripts/cibuild 

script: ./_scripts/cibuild

git:
  submodules: false

branches:
  only:
  - gh-pages     

notifications:
 webhooks:
    urls:
      - https://webhooks.gitter.im/e/b907f0e1ee5f192cba70
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
