permalink: /notes/:year/:month/:day/:title
markdown: kramdown
timezone: 'Europe/Berlin'

github:
  repo: "thekkedam/dd"
  branch: "gh-pages"

# Exclude personal
exclude:
  - _drafts
  - build
  - update
  - _toolScripts
  - deploy
  - vendor

