# You
name: Deepthi Devaki Akkoorath

# Modified time
date: 2015-12-02 14:44:14 UTC

# Show this in the footer
copyright: All rights reserved

permalink: /notes/:year/:month/:day/:title
markdown: kramdown
