# Website settings
baseurl: "/"
base_url: "https://dd.thekkedam.org"
url: "https://dd.thekkedam.org"
domain: "dd.thekkedam.org"
production: true

# Jekyll build settings
paginate: 6
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed  
highlighter: rouge
timezone: 'Europe/Berlin'

# Need to change this
#feed:
#  path: atom.xml

# TO start using
jekyll-mentions:
  base_url: https://twitter.com

# Exclude personal
exclude:
  - build
  - deploy
  - docker-compose.yml
  - Dockerfile
  - dynabuild.txt
  - Gemfile
  - Gemfile.lock
  - run-cmd.log
  - tests
  - update
  - versions.json
  - ToDO.md

# include
include:
  - ".htaccess"
  - ".message"

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jemoji
  - jekyll-avatar
  - jekyll-seo-tag
  - rouge
