# You
name: Deepthi Devaki Akkoorath

# Modified time
date: 2015-12-02T15:01:42+0000

# Show this in the footer
copyright: All rights reserved

permalink: /notes/:year/:month/:day/:title
markdown: kramdown
