# You
name: Deepthi Devaki Akkoorath
id: deepthidevaki
# Show this in the footer
copyright: All rights reserved
# Site Name
sitename: Deepthi Devaki
# Resume PDF link
pdfresume: /files/Akkoorath_Deepthi-Devaki_CV.pdf
# Google Analatic id
ga: UA-70817718-1
# Domain name
domain: dd.thekkedam.org
