version: "1.2"
# Bio settings
short_name: "Deepthi"
name_short: "Deepthi Akkoorath"
first_name: "Deepthi Devaki"
last_name: "Akkoorath"
full_name: "Deepthi Devaki Akkoorath"
gender: "female"
location: "Kaiserslautern"
job: "Research Assistant"
slogan: "If you can't explain it simply, you don't understand it well enough. - Albert Einstein"
description: "The home page of Deepthi Devaki Akkoorath."
keywords: "Scalable Distributed Systems, Concurrent Programming, Edge computing, Eventual consistency, CRDT, Causal consistency, Weak consistency, Software Transactional Memory"
thumbnail_path: "DeepthiDevakiAkkoorath.jpg"
thumbnail_path_s: "DeepthiDevakiAkkoorath_s.jpg"
user_ico_path: "Deepthi_Devaki_Akkoorath_logo.jpg"
bitcoin_address: 
site_admin: "Vipin Madhavanunni"

# direct links 
about: "/about-site"
license: "/LICENSE"
cms: "/cms.html"
feed: "/feed.xml"
sitemap: "sitemap.xml"
search: "/search"
privacy: "/privacy"
opensearch: "/search/opensearch.xml"
website_repo_url: "https://github.com/thekkedam/dd"
resume_path: "/assets/documents/cv/Akkoorath_Deepthi-Devaki_CV.pdf"
base_favicon_url: "/assets/img/icons/favicon" 
utm: "utm_source=dd.thekkedam.org&utm_medium=Website&utm_content=textlink&ref=dd.thekkedam.org"

# Image CDN
cdn:
  state: "disable"
  url: "https://cdn.rawgit.com"
  image: "thekkedam/dd/gh-pages/assets/img"

github:
  repo: "thekkedam/dd"
  branch: "gh-pages"

#fb
fb: deepthi.devaki
# disqus id
id: deepthidevaki
# Google Analatic id
ga: UA-70817718-1
# Google Custom Search
gcs: "010555979106730228922:r0o2cyogtfu"
# Google tag manager
gtm: "GTM-PWWLD7J"

# robots.txt 
disallow:
  - BingSiteAuth.xml
  - cms.html
  - CNAME
  - LICENSE/
  - nortonsw_26518600-9b7f-0.html
  - yandex_cc5b775180faf832.html
  - speaking/
  - skype.html
  - 200.html
  - 404.html
  - .htaccess
  - .message
  - upup.js
  - sw.js
  - assets/css/
  - assets/fonts/
  - assets/js/
  - cdn-cgi/
  - search/
  - privacy/
  - contact/thanks.html
  - writing/
  - writing/popular/
  - writing/video/
  - writing/wish/
  - writing/tags/
  - writing/articles/
  - photos/
  - blog
  - ToDO/
