Remix of:
     - '<a href="http://www.ybrikman.com/">Yevgeniy Brikman</a>'
     - '<a href="http://jmcglone.com/">Jonathan McGlone</a>'
     - '<a href="https://github.com/philipithomas/jekyll-resume">jekyll-resume</a>'
     - '<a href="https://github.com/vrypan/jekyll-post-via-web">Post via web</a>'
Using:
     - 'Icons <a href="http://fortawesome.github.io/Font-Awesome/">Font Awesome</a>.'
     - 'Writen by <a href="https://app.grammarly.com/">Grammarly</a>.'
Hosted:
     - 'On <a href="https://github.com/thekkedam/dd" title="This site hosted on GitHub">GitHub</a> with <a href="http://pages.github.com/" title="GitHub Pages">GitHub Pages</a>.'
     - 'IPv6, https support and made faster by <a href="https://www.cloudflare.com/">CloudFlare</a>.'
     - 'Images are served by <a href="http://rawgit.com/">RawGit</a> CDN.'
And:
     - 'Marked up with <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fdd.thekkedam.org%2F" title="HTML5 Validator">W3C validated HTML5</a>'
     - '<a href="http://www.w3.org/TR/WCAG20/" title="WCAG 2.0">WCAG 2.0</a> compliant.'
     - 'Powered by <a href="http://jekyllrb.com/" title="Jekyll">Jekyll</a>.'
     - 'The site contents/source <a rel="license" href="/LICENSE/">License details</a>.'


