#!/usr/bin/env bash -x
set -e # halt script on error

bundle exec jekyll build
htmlproofer ./_site --check-favicon --check-html --check-img-http --check-opengraph --report-invalid-tags --report-missing-names --report-script-embeds --disable-external
